### ISSUE TITLE
I cannot obtain the size of touch points on Ubuntu 20.04,but the Ubuntu 16.04 is ok.

### ISSUE THREAD

**Issue by NewZhg** [canonical/cn.ubuntu.com#658]
I cannot obtain the size of touch points on Ubuntu 20.04,but the Ubuntu 16.04 is ok.
The current acquisition method is as follows，
bool GraphicsView::viewportEvent(QEvent *event)
{
QEvent::Type type = event->type();

if(type == QEvent::TouchBegin || type == QEvent::TouchUpdate
|| type == QEvent::TouchEnd){

QTouchEvent *pTouchEvent = static_cast(event);
QList touchPoints = pTouchEvent->touchPoints();

int nId = 0;
QColor penColor;

foreach (const QTouchEvent::TouchPoint tp, touchPoints) {

qDebug() << "id" << tp.id() << "size" << tp.ellipseDiameters() << "position" << tp.pos();
}
return true;
}

return QGraphicsView::viewportEvent(event);
}

**Comment by sowasred2012** [comment]
Hi @NewZhg, thanks for raising this, but this repo is for the cn.ubuntu.com website, not Ubuntu itself - you can raise issues for Ubuntu here: https://launchpad.net/ubuntu
