### ISSUE TITLE
Empty links on Ubuntu Core特点概览

### ISSUE THREAD

**Issue by tjc713** [canonical/cn.ubuntu.com#664]
I found 4 links not working on https://cn.ubuntu.com/internet-of-things/core/features

The current links and correct links are:

- OTA 更新
  - https://cn.ubuntu.com/internet-of-things/features/ota-updates >> https://cn.ubuntu.com/internet-of-things/core/features/ota-updates
- 安全启动
  - https://cn.ubuntu.com/internet-of-things/features/secure-boot >> https://cn.ubuntu.com/internet-of-things/core/features/secure-boot
- 全盘加密
  - https://cn.ubuntu.com/internet-of-things/features/full-disk-encryption >> https://cn.ubuntu.com/internet-of-things/core/features/full-disk-encryption
- 恢复模式
  - https://cn.ubuntu.com/internet-of-things/features/recovery >> https://cn.ubuntu.com/internet-of-things/core/features/recovery

thanks

![image](https://user-images.githubusercontent.com/118874406/210477604-2e512db5-e28c-44f6-93fd-97cb7f083a95.png)
![image](https://user-images.githubusercontent.com/118874406/210477641-dc5b60cb-1613-48af-842b-b98295b82a39.png)

**Comment by zprood** [comment]
Thank you for the feedback, working on the fix.

**Comment by zprood** [comment]
The fix is applied at https://github.com/canonical/cn.ubuntu.com/pull/665

**Comment by carkod** [comment]
Hey @zprood I’m using Zenhub in GitHub, [click this link](https://app.zenhub.com/workspaces/-sites-tribe-5931746dba512f05402b61f6/board) to join my workspace and see other features available in GitHub or [download the Zenhub extension](https://www.zenhub.com/extension) and sign up with your GitHub account.
  _Posted using [Zenhub](https://www.zenhub.com)_
