### ISSUE TITLE
Update JS Script for populating the utm fields for forms.

### ISSUE THREAD

**Issue by Beatrijsb** [canonical/cn.ubuntu.com#669]
The webforms are not sending the utms correctly to the Marketo forms, so these leads are tagged as _otherchannel. 

Solution: find small JS script on ubuntu.com which populates the utm fields forms if present as a param in the URL.

**Comment by carkod** [comment]
@zprood do the utms work for visitors in China? I'd assume google analytics doesn't provide the right statistics, since it's blocked by firewall there.

**Comment by zprood** [comment]
@carkod UTM works in China with GA. The problem we found was if the visitors disagreed with the cookies policy on the first visit, there was no accurate data.
