### ISSUE TITLE
Page description error

### ISSUE THREAD

**Issue by Lonely-shang** [canonical/cn.ubuntu.com#675]
[https://cn.ubuntu.com/download/raspberry-pi](https://cn.ubuntu.com/download/raspberry-pi) The location of the label below for this link is incorrect
![image](https://user-images.githubusercontent.com/34124930/216528410-200288ac-7215-4f43-ae9f-cb4421e81987.png)

**Comment by carkod** [comment]
@zprood what would be the correct text here?

**Comment by zprood** [comment]
@carkod Yes, the text is not correct. Updated.
