### ISSUE TITLE
无线网络连接了不可使用

### ISSUE THREAD

**Issue by tqy845** [canonical/cn.ubuntu.com#676]
## Summary

[please describe the issue]
从LTS版本升级到22.10后wifi连接了，但是不能访问网络，但是可以用网线使用，由于我是笔记本这对我的工作产生了很大的影响

## Process

[list the steps to replicate the issue]
升级重启后即出现该问题，尝试直接安装22.10仍然如此，重启无效

## Current and expected result

[describe what happened and what you expected]
无线网卡没有按照预期那样工作

## Screenshot

[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/77242561/216892691-4ee5db43-ae90-48a1-b3d4-5cd17c54ab98.png)
由于截图不联网无法上传，这里没有提供无法联网的截图。
![image](https://user-images.githubusercontent.com/77242561/216892876-6969bdec-57db-4a40-903e-dbe3f632d1fa.png)

**Comment by zprood** [comment]
一般Linux上无线网络问题需要确认下自己的无线网卡芯片、Linux内核的驱动支持情况。然后根据实际情况编译安装对应驱动（无上游Linux内核驱动：如Realtek芯片）或升级内核（有上游内核驱动：如Intel，MediaTek）。
另外华为的机器目前不是官方认证型号，如碰到硬件Ubuntu系统兼容性问题，需要自己或者到社区找方法或去给华为反馈。
此问题与网站内容无关，先关闭。
