### ISSUE TITLE
laptop screen sometimes flickers and sometimes is normal

### ISSUE THREAD

**Issue by NoNameJe** [canonical/cn.ubuntu.com#688]
## Summary

[please describe the issue]
laptop screen sometimes flickers and sometimes is normal after install ubuntu.The screen is normal in windows 7.
But when i reboot in recovery mode,and in Recovery Menu, select resume ,then boot,the screen is normal.
PC : HP Pavilion  g4-2218TX(C9L86PA) 
CPU:i3 3110M
GPU:     INTEL HD 4000        + AMD Radeon HD 7670M
## Process

[list the steps to replicate the issue]
1.complete install ubuntu 22.04.02 lts
2.boot in normal mode
## Current and expected result

[describe what happened and what you expected]
I have try to install intel graphics driver ,but nothing change.
I also change screen solution,The frequency and amplitude of the screen flicker have decreased.
## Screenshot

[if relevant, include a screenshot]
![image](https://user-images.githubusercontent.com/121704683/230825602-5b2e40c6-2395-4ec4-9333-c6b71d4e136d.png)

**Comment by zprood** [comment]
This repo is just for the Ubuntu website issues tracking. Not for the system issues reporting. The HP Pavilion g4-2218TX is not a certified model. Please find the workaround in the community or Launchpad. 

Close it.

**Comment by NoNameJe** [comment]
i disable.amd graphics driver then its ok

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
