### ISSUE TITLE
Ubuntu 23.04新安装后的问题

### ISSUE THREAD

**Issue by virtual163** [canonical/cn.ubuntu.com#690]
## Summary

[please describe the issue]
不管是ubuntu22.04的桌面版还是Server版本都是相同的问题。
1、新系统用虚拟机安装， 安装完成后，安装openssh-server 安装后修改sshd_config文件无效， 默认端口修改失败，
2、新系统用ThinkPad T14 Gen2笔记本安装后，系统启动失败。
ssh配置文件的修改方式如下：
https://forum.ubuntu.org.cn/viewtopic.php?t=493946
## Process

[list the steps to replicate the issue]

## Current and expected result

[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by zprood** [comment]
这里不讨论系统使用问题，建议到 launchpad 或者论坛看看。先关闭了。
