### ISSUE TITLE
23.04server版本修改ssh远程端口无法生效

### ISSUE THREAD

**Issue by YZTM38106666** [canonical/cn.ubuntu.com#700]
vim /etc/ssh/sshd_config
Port 6666
保存退出
systemctl restart sshd
ufw allow 6666/tcp
systemctl status sshd
显示结果： Server listening on :: port [22.（端口没有修改成功）
![image](https://github.com/canonical/cn.ubuntu.com/assets/85061614/60050278-8045-4bc6-894f-ed97571b9732)
<img width="514" alt="image" src="https://github.com/canonical/cn.ubuntu.com/assets/85061614/eb969e91-4cbd-4539-91d9-e48609b48dca">

**Comment by zprood** [comment]
本仓库仅支持网站内容问题反馈，系统问题建议到 Launchpad 或者 Askubuntu 看看。先关闭了。
