### ISSUE TITLE
Translation error on the Chinese official website

### ISSUE THREAD

**Issue by zholey** [canonical/cn.ubuntu.com#710]
## Summary

Translation error on the Chinese official website

## Process

1. Open link address:  https://cn.ubuntu.com/
2. Scroll down the page and find the title "显着的企业节省"

## Current and expected result

the word "显着" is incorrect, it should be "显著"

## Screenshot

![image](https://github.com/canonical/cn.ubuntu.com/assets/20092117/7d4c96a1-e088-475c-91f6-9d8b5ac3e183)

**Comment by britneywwc** [comment]
Thanks for reporting, this has been fixed in #720. Will close this ticket as resolved.
