### ISSUE TITLE
Chinese pages stays outdated. P

### ISSUE THREAD

**Issue by tazkeung** [canonical/cn.ubuntu.com#714]
## Summary

Ubuntu download site of Chinese  remains old information.

## Process

1.Open https://cn.ubuntu.com/download/desktop
2.Read

## Current and expected result

Current: the newest version of Ubuntu is 23.04
Expected:update the information to make the newest version of Ubuntu 23.10.

## Screenshot
![IMG_0208](https://github.com/canonical/cn.ubuntu.com/assets/3472005/b9f46ac1-e3b8-4a29-98e1-5fb805ca2abf)

**Comment by britneywwc** [comment]
Hi @tazkeung, the Ubuntu version on the website has been updated now, will close this issue as resolved. Thank you!
