### ISSUE TITLE
ubuntu-23.10-desktop-amd64.iso.torrent Not Found

### ISSUE THREAD

**Issue by RainoutOvO** [canonical/cn.ubuntu.com#716]
## Summary

ubuntu-23.10-desktop-amd64.iso.torrent Not Found

## Process

![image](https://github.com/canonical/cn.ubuntu.com/assets/102637907/2d11fb2c-d5e0-4678-bd82-b2c3970f2567)

**Comment by britneywwc** [comment]
Hi @RainoutOvO, the website and download links have been updated now. I will close this issue as resolved, feel free to reopen if the issue persists. Thank you!
