### ISSUE TITLE
新的 libc6:i386 软件包 pre-installation 脚本 子进程返回错误状态 2

### ISSUE THREAD

**Issue by zihuamiao** [canonical/cn.ubuntu.com#728]
#dpkg: 处理归档 /var/cache/apt/archives/libc6_2.35-0ubuntu3.6_i386.deb (--unpack)
时出错：
 新的 libc6:i386 软件包 pre-installation 脚本 子进程返回错误状态 2
在处理时有错误发生：
 /var/cache/apt/archives/libc6_2.35-0ubuntu3.6_amd64.deb
 /var/cache/apt/archives/libc6_2.35-0ubuntu3.6_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

下列软件包有未满足的依赖关系：
 libc6-dbg : 依赖: libc6 (= 2.35-0ubuntu3.6) 但是 2.35-0ubuntu3 已经安装
 libc6-dev : 依赖: libc6 (= 2.35-0ubuntu3.6) 但是 2.35-0ubuntu3 已经安装
 libc6-i386 : 依赖: libc6 (= 2.35-0ubuntu3.6) 但是 2.35-0ubuntu3 已经安装
 libc6-x32 : 依赖: libc6 (= 2.35-0ubuntu3.6) 但是 2.35-0ubuntu3 已经安装
 libcom-err2:i386 : 依赖: libc6:i386 (>= 2.28) 但是它还没有被安装
 libcrypt1:i386 : 依赖: libc6:i386 (>= 2.25) 但是它还没有被安装
 libgcc-s1:i386 : 依赖: libc6:i386 (>= 2.35) 但是它还没有被安装
 libgssapi-krb5-2:i386 : 依赖: libc6:i386 (>= 2.33) 但是它还没有被安装
 libidn2-0:i386 : 依赖: libc6:i386 (>= 2.34) 但是它还没有被安装
 libk5crypto3:i386 : 依赖: libc6:i386 (>= 2.33) 但是它还没有被安装
 libkeyutils1:i386 : 依赖: libc6:i386 (>= 2.7) 但是它还没有被安装
 libkrb5-3:i386 : 依赖: libc6:i386 (>= 2.34) 但是它还没有被安装
 libkrb5support0:i386 : 依赖: libc6:i386 (>= 2.34) 但是它还没有被安装
 libnsl2:i386 : 依赖: libc6:i386 (>= 2.33) 但是它还没有被安装
 libnss-nis:i386 : 依赖: libc6:i386 (>= 2.4) 但是它还没有被安装
 libnss-nisplus:i386 : 依赖: libc6:i386 (>= 2.4) 但是它还没有被安装
 libssl3:i386 : 依赖: libc6:i386 (>= 2.34) 但是它还没有被安装
 libtirpc3:i386 : 依赖: libc6:i386 (>= 2.34) 但是它还没有被安装
 libunistring2:i386 : 依赖: libc6:i386 (>= 2.34) 但是它还没有被安装

**Comment by britneywwc** [comment]
Hi @zihuamiao, thank you for raising an issue. This seems to be an installation issue related to Ubuntu OS, not issues against our website cn.ubuntu.com. Please report the issue [here](https://help.ubuntu.com/community/ReportingBugs) to get the relevant teams involved.

Thank you.
