### ISSUE TITLE
Is Ubuntu 22.04 LTS support intel X86 64 platform?

### ISSUE THREAD

**Issue by Yuchiehchiu** [canonical/cn.ubuntu.com#738]
## Summary

Is Ubuntu 22.04 LTS support intel x86 64 platform?

[please describe the issue]
As Ubuntu 22.04.5 LTS (Jammy Jellyfish) is AMD64 only based, I would like to know what if Intel 64 can be supported? 

## Process
Codename: jammy
Version: 22.04
Date: Fri, 06 Sep 2024 18:42:52 UTC
Architectures: amd64

[list the steps to replicate the issue]

## Current and expected result

Please send a mail to grace.chiu@asuscloud.com, thanks.
[describe what happened and what you expected]

## Screenshot

[if relevant, include a screenshot]

**Comment by britneywwc** [comment]
Hi @Yuchiehchiu, this is not an issue related to cn.ubuntu.com. In terms of support, you can check on our help page here: https://help.ubuntu.com/community/SupportedArchitectures.
